version: 2

models: 
  - name: dim_users
    description: "Users dimension table ... "
    columns:
      - name: user_guid
        description: "This is the user unique id for the table"
        tests:
          - unique
          - not_null
  - name: dim_orders
  - name: fct_orders
  - name: fct_user_orders